apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |-
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'flask-app'
        static_configs:
          - targets: ['flask-app-service:5000']
      - job_name: 'nginx'
        static_configs:
          - targets: ['nginx-service:80'] 
  alerting_rules.yml: |
    # Include alert rules here
