apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-dep
  labels:
    app: flask-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
        - name: flask-app
          image: sanjeevkt720/prometheus-demo
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
  labels:
    job: fk-app
    app: flask-app
spec:
  type: ClusterIP
  selector:
    app: flask-app
  ports:
    - name : web
      protocol: TCP
      port: 3000
      targetPort: 3000
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata: 
  name: flask-servicemonitor
  labels: 
    release: prometheus
    app: prometheus
spec:
  jobLabel: job
  endpoints: 
    - interval: 15s
      port: web
      path: /swagger-stats/metrics
  selector:
    matchLabels:
      app: flask-app
