apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  labels:
    app: myapp
    type: front-end
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      name: myapp-prod
      labels:
        app: flask-app
        type: front-end
    spec:
      containers:
        - name: flask-app
          image: ashniike/pyyflask
          ports:
            - containerPort: 5000
